blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView


app_name="blog"

urlpatterns = [
    path('',BlogListView.as_view(), name='home'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name = "home"),
    path('blog/',include('blog.urls', namespace='blog')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('donations/', include('donations.urls', namespace='donations')),
    
]

donations/urls.py
from django.urls import path
from . import views

app_name="donations"

urlpatterns = [
    #path('', DonateView.as_view(), name='donations'),
    path('', views.index, name="donations"),
    path('charge/', views.charge, name="charge"),
    path('create-checkout-session/', views.CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('success/', views.successMsg, name='success'),
    path('cancel/', views.cancelMsg, name='cancel'),
]

blog/models.py
from django.db import models

# Create your models here.

#Modelo Post 
class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title
    

donations/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy


# Create your views here.

class BlogListView(View):
    def get(self, request,*args,**kwargs):
        posts = Post.objects.all()
        context={
            'posts':posts

        }   
        return render(request, 'blog_list.html', context)
    
class BlogCreateView(View):
    def get(self, request,*args,**kwargs):
        form=PostCreateForm()
        context={
        'form': form


        }
        return render(request, 'blog_create.html', context)
    
    def post(self, request,*args,**kwargs):
        if request.method == "POST":
            form= PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')

            context = {
            
        }
        return render(request, 'blog_create.html', context)
    
class BlogDetailView(View):
    def get(self,request, pk, *args,**kwargs):
        post = get_object_or_404(Post, pk=pk)
        context={
            'post':post


        }
        return render(request,'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model=Post
    fields=['title','content']
    template_name='blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url= reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render 


class HomeView(View):
    def get(self, request,*args,**kwargs):
        context={


        }

        return render(request, 'index.html', context)
        

donations/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.conf import settings
from django.views import View
import stripe


stripe.api_key = settings.STRIPE_SECRET_KEY


def index(request, *args, **kwargs):
    context = {
        # Puedes agregar datos dinámicos aquí si es necesario
    }
    return render(request, 'Donations/donations.html', context)


class CreateCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        amount = int(request.POST.get("amount", 1))  # en dólares
        if amount < 1:
            amount = 1

        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': 'mxn',
                    'product_data': {
                        'name': 'Donación',
                        
                    },
                    'unit_amount': amount * 100,  # Stripe usa centavos
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url=request.build_absolute_uri('/donations/success/'),
            cancel_url=request.build_absolute_uri('/donations/cancel/'),
            locale='en',
        )
        return redirect(session.url, code=303)
    

def charge(request, *args, **kwargs):
    amount = 5
    if request.method == 'POST':
        print('Data:', request.POST)
    return redirect(reverse('donations:success', args=[amount]))

def successMsg(request, *args, **kwargs):
    amount = args[0] if args else 0
    return render(request, 'Donations/success.html', {'amount': amount})


def cancelMsg(request):
    return render(request, 'Donations/cancel.html')

templates/Donations/cancel.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>title</title>
</head>
<body>
<h1 class="text-2xl font-bold text-red-600">Pago cancelado.</h1>

<a href="{% url 'donations:donations' %}">Volver a donaciones</a>
</body>
</html>

templates/Donations/donations.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Prueba</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Aquí enlazas tu CSS de Tailwind -->
  <link href="{% static 'css/output.css' %}" rel="stylesheet">
</head>

<body class="bg-gray-50 font-serif leading-normal tracking-normal p-8">

  {% block content %}
    <h1 class="text-4xl font-bold text-blue-700 mb-6">Donaciones</h1>
<a href="#" class="text-lg text-white bg-green-500 px-6 py-3 rounded shadow hover:bg-green-600 transition">
</a>


  <form action="{% url 'donations:create_checkout_session' %}" method="POST" class="space-y-4">
    {% csrf_token %}
    <label for="amount" class="block text-lg font-semibold">¿Cuánto deseas donar?</label>
    <input type="number" name="amount" id="amount" min="1" step="1"
           class="border rounded px-4 py-2 w-full" placeholder="Ej. 20 MXN">
    <button  href: type="submit" class="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700">
        Donar
    </button>
</form>
<br>

<a href="{% url 'home' %}">Volver al inicio</a>

  {% endblock content %}

</body>
</html>

templates/Donations/success.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>title</title>
</head>
<body>
<h1 class="text-2xl font-bold text-green-600">¡Gracias por tu donación!</h1>

<a href="{% url 'donations:donations' %}">Volver al inicio</a>

</body>
</html>

templates/Donations/template.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Donations 
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">

        {% block content %}
		
		Template HTML
		
		{% endblock content %}

		

	</body>

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">

        {% block content %}{% endblock content %}

	</body>
</html>

templates/blog_create.html
<form method="POST">
{% csrf_token %}
Title {{form.title}}
<br>
content{{form.content}}
<button type"submit">Submit</button>
</form>

templates/blog_delete.html
<form method="POST">
{% csrf_token %}
{{form}}
<br>
<button type"submit">Delete</button>
</form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

<p><a href="{% url 'blog:update' post.id %}">Update</a></p>
<br>
<p><a href="{% url 'blog:delete' post.id %}">Delete</a></p>
<br>
<a href="{% url 'blog:home' %}">Volver al inicio</a>

templates/blog_list.html
{% extends "base.html" %}

{% block content %}
<br>
<a class="focus:outline-none text-white bg-red-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900"<h1> Blog list </h1> </a>
<br>
<br>
{% for post in posts %}
<br>
<p><a class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" href="{% url "blog:detail" post.id %}">{{post.title}}</a></p>
{% endfor %}
<br>
<br>
<a  class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"href="{% url 'blog:create' %}">Create</a>

{% endblock content %}

templates/blog_update.html
<h2>Editar Post </h2>
<form method="POST">
{% csrf_token %}
Title 
<br>
{{form.title}}
<br>
content
<br>
{{form.content}}
<br>
<button type"submit">Update</button>


</form>

templates/index.html
{% extends "base.html" %}

{% block content %}<h1>Hola Visita mi Blog <a class="text-red-600"  href="{% url 'blog:home' %}">   Aquí  </a></h1>
<br>
<a href="{% url 'donations:donations' %}">
  <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
    Donar
  </button>
</a>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>